Fix publish failure due to permissions
https://github.com/jquintus/WordleHelper/actions/runs/4331928933/jobs/7564080744#step:5:117

remote: Write access to repository not granted.
fatal: unable to access 'https://github.com/jquintus/WordleHelper.git/': The requested URL returned error: 403
Running post deployment cleanup jobs… 🗑️
/usr/bin/git worktree remove github-pages-deploy-action-temp-deployment-folder --force
Error: The deploy step encountered an error: The process '/usr/bin/git' failed with exit code 128 ❌
Deployment failed! ❌